management:
    security:
        enabled: false
security:
    basic:
        enabled: false

spring:
    autoconfigure:
        exclude: com.csys.csysstarter.hystrix.support.HystrixContextAutoConfiguration
    liquibase:
        default-schema: dbo
        enabled: false 
    jmx.enabled: true
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource: 
        url: jdbc:sqlserver://localhost\SQL2019;databaseName=basededonner
        username: sa
        password: 123
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        open-in-view: false
        show-sql: true
        hibernate:
            #ddl-auto: none
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.default_schema: dbo
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: hazelcast
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
            org.hibernate.envers.store_data_at_delete: true
    redis:
        host: localhost
        port: 6379
    mail:
        host: smtppro.tunet.tn
        port: 25
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false    
    jackson:
        serialization:
            write_dates_as_timestamps : false
lang:
    secondary: ar

     
#server:
#    servlet:
#        contextPath: /prod
#    port: 9800
server:
    servlet:
        contextPath: /template-core
    port: 9500
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024 
    session:
        timeout: 60
 
messages :
       basename: i18n/messages
email:
    from: bahloulfares100@gmail.com
    to: bahloulfares3@gmail.com

    
